version: "3.9"
    
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - mariadb_db_data:/var/lib/mysql
    # restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: looker
      MYSQL_USER: looker
      MYSQL_PASSWORD: looker
    ports:
      - 3306:3306
volumes:
  mariadb_db_data: 
